version: '3.8'

services:
  vault:
    image: hashicorp/vault:1.20.4
    container_name: vault
    ports:
      - "8200:8200"
      - "8201:8201"
    volumes:
      - ./config:/vault/config
      - ./data:/vault/data
    cap_add:
      - IPC_LOCK
    environment:
      VAULT_CONFIG_FILE: /vault/config/vault-config.hcl
      VAULT_ADDR: 'http://0.0.0.0:8200'
    command: server
    healthcheck:
      test: ["CMD", "vault", "status"]
      interval: 5s
      timeout: 10s
      retries: 5
  vault-init:
    image: hashicorp/vault:1.20.4
    container_name: vault-init
    depends_on:
      vault:
        condition: service_started
    volumes:
      - ./config:/vault/config
      - ./data:/vault/data
    entrypoint: /bin/sh /vault/config/setup.sh